# Generated by Django 6.1.1 on 2026-09-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('simulated', 'Simulated'), ('failed', 'Failed')], max_length=10)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academics.result')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
